services:
  nestjs-app:
    image: gustavoramirezledesma/nestjs-compose:1.0 
    build:
     context: .
     dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - postgres_bytebase_datatest
  
  postgres_bytebase_datatest:
    image: postgres
    restart: always
    container_name: postgres_bytebase_datatest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=byt1b2s3a4dm5n
      - POSTGRES_USER=bytebaseadmin
      - POSTGRES_DB=bytebasetest
      - POSTGRES_HOST_AUTH_METHOD=trust